# Generated by Django 3.2.13 on 2022-09-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.TextField(default='None'),
        ),
    ]
